In [1]:
from yelp_data import get_businesses, fetch_business_details, fetch_business_details_list

In [2]:
import requests
import pandas as pd

In [3]:
food_df = get_businesses("Los Angeles")

In [4]:
reviews_df = fetch_business_details_list("Los Angeles")

In [5]:
df1 = pd.DataFrame(food_df['businesses'])[['id', 'name', 'review_count', 'price', 'distance', 'categories']]
df2 = pd.DataFrame(reviews_df)[['id', 'text', 'business_id', 'rating']]
df3 = df1.merge(df2, right_on='business_id', left_on='id', how='left')
df3

,id_x,name,review_count,price,distance,categories,id_y,text,business_id,rating
0,-dmFlY8oohLiep_sexSMSg,Tita Lina’s,31,$$,4466.022084,"[{'alias': 'filipino', 'title': 'Filipino'}]",17vvltXjpJpZyTXENcdPYg,Josie-Arizona! Every time we're in LA. we must...,-dmFlY8oohLiep_sexSMSg,5
1,-dmFlY8oohLiep_sexSMSg,Tita Lina’s,31,$$,4466.022084,"[{'alias': 'filipino', 'title': 'Filipino'}]",XrrZ0VCx0UQT3F6MJTf8TA,Honestly this was one of the Best cheap meals ...,-dmFlY8oohLiep_sexSMSg,5
2,-dmFlY8oohLiep_sexSMSg,Tita Lina’s,31,$$,4466.022084,"[{'alias': 'filipino', 'title': 'Filipino'}]",DlxQDA6t33xmo5NW1kyUTw,First time eating hear today with wifey. This ...,-dmFlY8oohLiep_sexSMSg,5
3,XgQ8riUvnMOBVfRG29NCEQ,Anju House,70,NaN,1584.356709,"[{'alias': 'korean', 'title': 'Korean'}]",hW30bLO7cW_oSxXzS02X7w,A LA must try. I stopped for a quick bite befo...,XgQ8riUvnMOBVfRG29NCEQ,5
4,XgQ8riUvnMOBVfRG29NCEQ,Anju House,70,NaN,1584.356709,"[{'alias': 'korean', 'title': 'Korean'}]",AC61LQgExLBn5twAgxfKmQ,Great food and great ambience. It feels like a...,XgQ8riUvnMOBVfRG29NCEQ,5
5,XgQ8riUvnMOBVfRG29NCEQ,Anju House,70,NaN,1584.356709,"[{'alias': 'korean', 'title': 'Korean'}]",zLSZI81_Nlr7ZEmWH-rbyw,Came here w friend for our biweekly work dinne...,XgQ8riUvnMOBVfRG29NCEQ,5
6,mrEgKltVkacoD6ZNWzQjyg,Bang Bang Noodles,386,$$,7834.339447,"[{'alias': 'noodles', 'title': 'Noodles'}, {'a...",Mv1nXAGfv9CfMq3ZqqQgUg,I'd been looking for a noodle place like this ...,mrEgKltVkacoD6ZNWzQjyg,4
7,mrEgKltVkacoD6ZNWzQjyg,Bang Bang Noodles,386,$$,7834.339447,"[{'alias': 'noodles', 'title': 'Noodles'}, {'a...",TTjnF-bAgQuobcRHQH0_Gg,I've always loved bang bang since their pop up...,mrEgKltVkacoD6ZNWzQjyg,5
8,mrEgKltVkacoD6ZNWzQjyg,Bang Bang Noodles,386,$$,7834.339447,"[{'alias': 'noodles', 'title': 'Noodles'}, {'a...",7L5QDHQjdVSLtswDWjqPCQ,Food: I ordered the szechuan garlic noodles w/...,mrEgKltVkacoD6ZNWzQjyg,5
9,oZG16DktFsm-Sl-KDSny_g,Katsu Sando,348,$$,7630.503329,"[{'alias': 'sandwiches', 'title': 'Sandwiches'...",7Li9QgW57J99MvbEuj6w0w,Takeout spot in Chinatown that's more of a gra...,oZG16DktFsm-Sl-KDSny_g,5
10,oZG16DktFsm-Sl-KDSny_g,Katsu Sando,348,$$,7630.503329,"[{'alias': 'sandwiches', 'title': 'Sandwiches'...",8dvrKmW3bncv9thppczP9g,"On one of the main streets in Chinatown, there...",oZG16DktFsm-Sl-KDSny_g,4
11,oZG16DktFsm-Sl-KDSny_g,Katsu Sando,348,$$,7630.503329,"[{'alias': 'sandwiches', 'title': 'Sandwiches'...",1xNvRMBwnfBAE2jCUMqNjg,1 star for the good cheese and curry. The rest...,oZG16DktFsm-Sl-KDSny_g,1
12,zescAlXv7_bcqcxi38ZeHw,Kuya Lord,165,$$,2692.387360,"[{'alias': 'bbq', 'title': 'Barbeque'}, {'alia...",S_AlGRAb3UPxUvYgYs_Smg,"Lunch: Prawns, java rice, lucenachon were exce...",zescAlXv7_bcqcxi38ZeHw,5
13,zescAlXv7_bcqcxi38ZeHw,Kuya Lord,165,$$,2692.387360,"[{'alias': 'bbq', 'title': 'Barbeque'}, {'alia...",_WBZnX1sUiswuDibCWxcZg,Let me start by saying that I took the time to...,zescAlXv7_bcqcxi38ZeHw,5
14,zescAlXv7_bcqcxi38ZeHw,Kuya Lord,165,$$,2692.387360,"[{'alias': 'bbq', 'title': 'Barbeque'}, {'alia...",eK6fBlbCbnoNmPi1XIQbJA,Shop was very small. You order at the counter ...,zescAlXv7_bcqcxi38ZeHw,4
15,kjJT0aclLYI291W0V1DKVg,Pine & Crane DTLA,386,$$,5911.994252,"[{'alias': 'taiwanese', 'title': 'Taiwanese'}]",WSY8lZ3uhfPKnQr90AuoAg,Stopped by for breakfast after coming home fro...,kjJT0aclLYI291W0V1DKVg,5
16,kjJT0aclLYI291W0V1DKVg,Pine & Crane DTLA,386,$$,5911.994252,"[{'alias': 'taiwanese', 'title': 'Taiwanese'}]",vQRKvYkxexHjZW7yCzLUlw,Dan dan noodles: 4/5. Noodles were good. The f...,kjJT0aclLYI291W0V1DKVg,5
17,kjJT0aclLYI291W0V1DKVg,Pine & Crane DTLA,386,$$,5911.994252,"[{'alias': 'taiwanese', 'title': 'Taiwanese'}]",4CL-epP9xN-HYNfi6cpfYQ,"Line out door. Order first, pay and then sit, ...",kjJT0aclLYI291W0V1DKVg,5
18,HDMXGMBjLjWuPy7SrgRGHg,Zombie Chicken & Nolboo Spicy Noodle,1,NaN,1961.459218,"[{'alias': 'chicken_wings', 'title': 'Chicken ...",Po8OPTgCXuCD5yAZHTNsaQ,Yummy food and amazing grand opening special f...,HDMXGMBjLjWuPy7SrgRGHg,5
19,-5TFq3V--bffJGW000YuGQ,Holbox,873,$$,6307.523661,"[{'alias': 'latin', 'title': 'Latin American'}...",FdIsDG8Qf-zyyfE9NyST0w,The dishes in this restaurant are intricate in...,-5TFq3V--bffJGW000YuGQ,5
20,-5TFq3V--bffJGW000YuGQ,Holbox,873,$$,6307.523661,"[{'alias': 'latin', 'title': 'Latin American'}...",x8LQSGlNdKwINUj8eTJj4g,Tried it and wasn't disappointed - the best ch...,-5TFq3V--bffJGW000YuGQ,4
21,-5TFq3V--bffJGW000YuGQ,Holbox,873,$$,6307.523661,"[{'alias': 'latin', 'title': 'Latin American'}...",8p5uc2Busnaq2Zj7fArNPQ,"There is a 30 minute wait, but totally worth i...",-5TFq3V--bffJGW000YuGQ,5
22,ohosmz6FXVAeoW5nUkYwng,Pine & Crane,2943,$$,5193.619781,"[{'alias': 'taiwanese', 'title': 'Taiwanese'},...",Mu6qYfNKgoU6jGJaCZNR7A,"Service was excellent. Upbeat, bustling spot. ...",ohosmz6FXVAeoW5nUkYwng,4
23,ohosmz6FXVAeoW5nUkYwng,Pine & Crane,2943,$$,5193.619781,"[{'alias': 'taiwanese', 'title': 'Taiwanese'},...",zCL8ZcEXEkaQLliAqnvFGQ,I came here by recommendation of someone at Ae...,ohosmz6FXVAeoW5nUkYwng,5
24,ohosmz6FXVAeoW5nUkYwng,Pine & Crane,2943,$$,5193.619781,"[{'alias': 'taiwanese', 'title': 'Taiwanese'},...",KD8FZVN5JZxJuYwNKxuKKA,"Great service, friendly staff, and was able to...",ohosmz6FXVAeoW5nUkYwng,4
25,5LU6aNLDG10imXu3btmlcw,Annie's Soul Delicious,691,$$,2554.776764,"[{'alias': 'soulfood', 'title': 'Soul Food'}, ...",zRvjfAIAqHhlDqFe7Nb87w,"Amazing food, I absolutely love soul food and ...",5LU6aNLDG10imXu3btmlcw,5
26,5LU6aNLDG10imXu3btmlcw,Annie's Soul Delicious,691,$$,2554.776764,"[{'alias': 'soulfood', 'title': 'Soul Food'}, ...",m3fnzWE3M_Iy7CilZ2fPQw,Finally found good soul food in Los Angeles!\n...,5LU6aNLDG10imXu3btmlcw,5
27,5LU6aNLDG10imXu3btmlcw,Annie's Soul Delicious,691,$$,2554.776764,"[{'alias': 'soulfood', 'title': 'Soul Food'}, ...",TujDCKNUMPko6jT2Aqyzsw,I just want to say this is the best oxtails I ...,5LU6aNLDG10imXu3btmlcw,5

In [28]:
df3['categories'][4]

[{'alias': 'noodles', 'title': 'Noodles'},
 {'alias': 'popuprestaurants', 'title': 'Pop-Up Restaurants'}]

In [6]:
food_df

{'businesses': [{'id': '1GKQG1iVYYiatHFhV7GDpQ',
   'alias': 'juliana-los-angeles-los-angeles',
   'name': 'Juliana Los Angeles',
   'image_url': 'https://s3-media1.fl.yelpcdn.com/bphoto/A8Om57P5P8eCGDrvw3UtWw/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/juliana-los-angeles-los-angeles?adjust_creative=YNj8LQ2sLnfDp_InHUP7DA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=YNj8LQ2sLnfDp_InHUP7DA',
   'review_count': 39,
   'categories': [{'alias': 'breakfast_brunch', 'title': 'Breakfast & Brunch'},
    {'alias': 'lounges', 'title': 'Lounges'},
    {'alias': 'tapasmallplates', 'title': 'Tapas/Small Plates'}],
   'rating': 4.5,
   'coordinates': {'latitude': 34.063162, 'longitude': -118.2986},
   'transactions': ['restaurant_reservation'],
   'location': {'address1': '3500 W 6th St',
    'address2': None,
    'address3': '',
    'city': 'Los Angeles',
    'zip_code': '90020',
    'country': 'US',
    'state': 'CA',
    'display_address': ['3500 W 6th St', 'Los Angeles, CA 90020']},
   'phone': '+12135683035',
   'display_phone': '(213) 568-3035',
   'distance': 2104.216855954493},
  {'id': 'ggSWm7VIo3pKxHFv7Qxoiw',
   'alias': 'chuncheon-dakgalbi-donghae-makguksu-2-los-angeles',
   'name': 'Chuncheon Dakgalbi Donghae Makguksu 2',
   'image_url': 'https://s3-media2.fl.yelpcdn.com/bphoto/Ew3XZ59VQQFLdnUPk_bUiQ/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/chuncheon-dakgalbi-donghae-makguksu-2-los-angeles?adjust_creative=YNj8LQ2sLnfDp_InHUP7DA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=YNj8LQ2sLnfDp_InHUP7DA',
   'review_count': 37,
   'categories': [{'alias': 'korean', 'title': 'Korean'}],
   'rating': 4.5,
   'coordinates': {'latitude': 34.064012, 'longitude': -118.300574},
   'transactions': [],
   'location': {'address1': '3601 W 6th St',
    'address2': '',
    'address3': None,
    'city': 'Los Angeles',
    'zip_code': '90020',
    'country': 'US',
    'state': 'CA',
    'display_address': ['3601 W 6th St', 'Los Angeles, CA 90020']},
   'phone': '',
   'display_phone': '',
   'distance': 1931.38822133222}],
 'total': 24300,
 'region': {'center': {'longitude': -118.32138061523438,
   'latitude': 34.0615895441259}}}